// Part 3 §2: Test confidence screen.
export const TESTS_EYEBROW = 'Audit / Test confidence';
export const TESTS_TITLE = 'Measure confidence, not just coverage.';
export const TESTS_SUBTITLE = 'Connect tested branches to risky changes. Keep missing signals visible.';
export const TESTS_EVIDENCE = 'Coverage evidence';
export const TESTS_EXPORT = 'Export coverage gaps';
export const TESTS_CSV_FILENAME = 'branch-coverage-gaps.csv';
export const TESTS_CARD_COVERAGE = 'Branch coverage';
export const TESTS_CARD_COVERAGE_CAPTION = (covered: string, total: string): string => `${covered} / ${total} instrumented branches`;
export const TESTS_CARD_BELOW = 'Files below 60%';
export const TESTS_CARD_BELOW_CAPTION = 'Review priority depends on behaviour and change';
export const TESTS_CARD_RESULTS = 'Test results';
export const TESTS_CARD_RESULTS_CAPTION = (failing: string): string => `${failing} failing tests · sample test runs`;
export const TESTS_NO_TEST_FILES = 'No test files in this inventory.';
export const TESTS_CARD_MUTATION = 'Mutation score';
export const MUTATION_NOT_COLLECTED = 'Not collected · unknown, not zero';
export const TESTS_TABS_LABEL = 'Test confidence views';
export const TESTS_TAB_MAP = 'Coverage map';
export const TESTS_TAB_RESULTS = 'Test results';
export const TESTS_TAB_MUTATION = 'Mutation testing';
export const TESTS_MAP_TITLE = 'Coverage across the codebase';
export const TESTS_MAP_SUBTITLE = 'One tile per file. Select a tile to inspect its evidence.';
export const TESTS_MAP_FOOTNOTE = 'Coverage is execution evidence, not proof of assertions or correctness. Sample signals.';
export const TESTS_MAP_LABEL = 'Sample branch coverage, one tile per file';
export const TESTS_TILE_LABEL = (name: string, coverage: string): string => `${name}: ${coverage} branch coverage`;
export const TESTS_SHOWING = (n: number, total: number): string => `Showing the ${n} highest-priority of ${total} files.`;
export const TESTS_MODULES_TITLE = 'Branch coverage by module';
export const TESTS_MODULES_SUBTITLE = 'Weighted by instrumented branch count.';
export const TESTS_MODULES_HIDDEN = (n: number): string => `${n} smaller modules are not shown.`;
export const TESTS_MODULE_BAR_LABEL = (module: string, pct: string): string => `${module}: ${pct} branch coverage (sample)`;
export const TESTS_GAPS_TITLE = 'Coverage gaps worth investigating';
export const TESTS_GAPS_SUBTITLE = 'Files below 60% branch coverage, most-changed first.';
export const TESTS_GAPS_CAPTION = 'Coverage gaps';
export const TESTS_GAPS_NONE = 'No file with known coverage is below 60%.';
export const TESTS_COL_FILE = 'File';
export const TESTS_COL_BRANCHES = 'Covered / total';
export const TESTS_COL_COVERAGE = 'Coverage';
export const TESTS_COL_COMMITS = 'Commits / 90d';
export const TESTS_COL_ACTIONS = 'Actions';
export const TESTS_PLAN = 'Plan tests';
export const TESTS_PLANNED = 'Tests planned';
export const TESTS_PLAN_LABEL = (name: string): string => `Plan characterization tests for ${name}`;
export const TESTS_PLAN_TITLE = (name: string): string => `Characterize ${name} with tests`;
export const TESTS_PLAN_FAILED = 'Could not add this work item.';
export const TESTS_PLAN_ADDED = (name: string): string => `Test work item added for ${name}.`;
export const TESTS_RUNS_TITLE = 'Sample test runs';
export const TESTS_RUNS_SUBTITLE = (tests: string, passing: string, failing: string): string => `${tests} tests · ${passing} passing · ${failing} failing, per test file.`;
export const TESTS_RUNS_CAPTION = 'Sample test runs per test file';
export const TESTS_RUNS_NONE = 'No test files in this inventory, so there are no test runs to show.';
export const TESTS_COL_TESTS = 'Tests';
export const TESTS_COL_RESULT = 'Result';
export const TESTS_COL_MODULE = 'Module';
export const TESTS_COL_DURATION = 'Duration';
export const TESTS_RESULT_PASSING = 'Passing';
export const TESTS_RESULT_FAILING = (n: number): string => `${n} failing`;
export const TESTS_DURATION = (ms: number): string => `${(ms / 1000).toFixed(2)} s`;
export const TESTS_OPEN_FILE = 'Open file detail';
export const TESTS_SELECTED = (name: string): string => `Selected: ${name}`;
export const MUTATION_TITLE = 'Mutation testing';
export const MUTATION_SUBTITLE = 'No mutation-test provider is connected.';
export const MUTATION_EMPTY_TITLE = 'The strength of your assertions is unknown.';
export const MUTATION_EMPTY = 'There are no mutation-test results. Coverage alone cannot tell you whether tests detect meaningful changes.';
export const CONFIGURE_EVIDENCE = 'Configure evidence';
export const COVERAGE_BAND_LABEL: Readonly<Record<'low' | 'mid' | 'high' | 'unknown', string>> = {
  low: '< 60%', mid: '60–79%', high: '≥ 80%', unknown: 'Unknown',
};
export const TESTS_SOURCES_TITLE = 'Coverage evidence';
export const TESTS_SOURCE_LABELS = { coverage: 'Branch coverage', runs: 'Test runs', mutation: 'Mutation testing' } as const;
/** E14: every chart or map label that shows sample data says "sample". */
export const TESTS_MODULES_LABEL = 'Sample branch coverage by module';
