"""Browser interaction checks. Uses set_content because managed Chromium blocks URL navigation here."""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json
ROOT=Path(__file__).resolve().parents[1]
checks=[];errors=[];network=[]
def check(name,condition=True):
 assert condition,name
 checks.append(name)
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
 context=browser.new_context(viewport={'width':1600,'height':1050},device_scale_factor=1,accept_downloads=True)
 page=context.new_page();page.set_default_timeout(3500);page.on('pageerror',lambda e: errors.append(str(e)));page.on('request',lambda r: network.append(r.url))
 page.set_content((ROOT/'index.html').read_text(encoding='utf-8'),wait_until='load')
 def nav(route):
  page.evaluate('(r)=>CIPrototype.navigate(r)',route);page.wait_for_timeout(55)
 def act(action,scope=None):
  (scope or page).locator(f'[data-action="{action}"]').first.click()
 def shot(name):page.screenshot(path=str(ROOT/'screenshots'/f'{name}.png'))
 check('Initial city renders a canvas',page.locator('#city-stage canvas').count()==1)
 page.locator('[data-input="city-query"]').fill('CostEngine')
 check('City search matches one file','1 of 144' in page.locator('#city-count').inner_text())
 page.locator('[data-input="city-query"]').fill('no-such-file')
 check('City search supports no-result state','0 of 144' in page.locator('#city-count').inner_text())
 page.locator('[data-input="city-query"]').fill('')
 page.locator('[data-change="city-metric"]').select_option('coverage')
 page.locator('[data-change="city-height"]').select_option('loc')
 check('City metric controls update their legend','Source lines' in page.locator('.city-footer').inner_text())
 act('zoom-in');act('zoom-out');act('city-focus');act('city-reset')
 check('City camera controls do not throw')
 page.locator('[data-action="city-mode"][data-mode="map"]').click();shot('city-map-dark')
 check('Map representation renders',page.locator('#city-stage canvas').count()==1)
 page.locator('[data-action="city-mode"][data-mode="inventory"]').first.click()
 check('Inventory exposes every file',page.locator('#city-inventory tbody tr').count()==144)
 page.locator('#city-inventory [data-action="inspect"]').first.click()
 check('Inventory opens accessible file inspector',page.locator('[role="dialog"]').count()==1)
 shot('file-inspector-dark')
 page.keyboard.press('Escape');check('Escape closes modal',page.locator('[role="dialog"]').count()==0)
 page.locator('[data-action="city-mode"][data-mode="city"]').click()
 nav('architecture');page.locator('.graph-node[data-id="assets"]').click()
 check('Architecture node updates module inspector','Assets' in page.locator('#module-summary').inner_text())
 page.locator('[data-action="arch-tab"][data-tab="matrix"]').click()
 page.locator('[data-action="matrix-cell"][data-from="domain"][data-to="storage"]').click()
 check('Matrix preserves direction and evidence','3 observed import statements' in page.locator('#matrix-detail').inner_text())
 shot('architecture-matrix-dark')
 page.locator('[data-action="arch-tab"][data-tab="rules"]').click()
 check('Boundary rules are available',page.locator('tbody tr').count()==5)
 act('new-rule');page.locator('#rule-from').select_option('shared');page.locator('#rule-to').select_option('assets');page.locator('#rule-rationale').fill('Shared utilities stay independent.');act('save-rule')
 check('New intended rule is evaluated',page.locator('tbody tr').count()==6)
 page.locator('[data-change="arch-violations"]').check()
 check('Violations filter limits rules',page.locator('tbody tr').count()==1)
 page.locator('[data-change="arch-violations"]').uncheck()
 nav('quality');initial=page.evaluate('CIPrototype.total().issues')
 page.locator('[data-input="quality-query"]').fill('CostEngine')
 check('Finding search is scoped',page.locator('#quality-table tbody tr').count()==3)
 page.locator('[data-action="issue"]').first.click();shot('finding-review-dark');act('acknowledge-issue')
 check('Acknowledging a finding changes open count',page.evaluate('CIPrototype.total().issues')==initial-1)
 page.locator('[data-change="quality-status"]').select_option('Acknowledged')
 check('Acknowledged filter shows disposition',page.locator('#quality-table tbody tr').count()==1)
 page.locator('[data-action="issue"]').first.click();act('reopen-issue')
 check('Reopening restores open count',page.evaluate('CIPrototype.total().issues')==initial)
 act('quality-reset');page.locator('[data-action="issue"]').first.click();act('dismiss-issue')
 page.locator('#dismiss-reason').fill('Intentional public API in the fixture.');act('confirm-dismiss')
 check('Dismissal requires and records a reason',page.evaluate('Object.keys(CIPrototype.state.issueStatus).some(k=>k.endsWith("-reason"))'))
 nav('tests');page.locator('[data-action="test-tab"][data-tab="results"]').click();shot('test-results-dark')
 check('Test result tab displays failures','Failing' in page.locator('main').inner_text())
 page.locator('[data-action="test-tab"][data-tab="mutation"]').click();shot('mutation-unknown-dark')
 check('Missing mutation evidence is unknown','unknown' in page.locator('main').inner_text())
 nav('dependencies');page.locator('[data-input="dependency-query"]').fill('archive')
 check('Package search filters inventory',page.locator('#dependency-table tbody tr').count()==1)
 act('package-detail');check('Package detail labels fictional record','Fictional' in page.locator('[role="dialog"]').inner_text());page.keyboard.press('Escape')
 page.locator('[data-input="dependency-query"]').fill('');page.locator('[data-change="dependency-filter"]').select_option('Transitive')
 check('Dependency relationship filter works',page.locator('#dependency-table tbody tr').count()==2)
 page.locator('[data-action="dependency-tab"][data-tab="graph"]').click();shot('dependency-path-dark')
 page.locator('[data-action="dependency-tab"][data-tab="licenses"]').click();check('License screen distinguishes unresolved status','Unresolved' in page.locator('main').inner_text())
 nav('security');page.locator('[data-action="security-tab"][data-tab="secrets"]').click();act('secret-dismiss')
 check('Secret fixture disposition is stored',page.evaluate('CIPrototype.state.issueStatus["demo-secret"]')=='Fixture')
 nav('evolution');page.locator('[data-action="evolution-range"][data-range="30 days"]').click()
 check('History window changes',page.evaluate('CIPrototype.state.evolutionRange')=='30 days')
 act('compare');shot('snapshot-comparison-dark');act('use-snapshot')
 check('Baseline selection changes data',page.evaluate('CIPrototype.state.snapshot')=='baseline')
 page.locator('[data-change="snapshot"]').select_option('current')
 nav('workbench');n=page.evaluate('CIPrototype.state.tasks.length');act('new-task')
 page.locator('[name="title"]').fill('QA test: protect the cost boundary');page.locator('[name="status"]').select_option('Planned');act('save-task')
 check('Creating work item adds a persistent state entry',page.evaluate('CIPrototype.state.tasks.length')==n+1)
 tid=page.evaluate('CIPrototype.state.tasks.at(-1).id')
 page.locator(f'[data-action="task-detail"][data-id="{tid}"]').click();page.locator('[name="status"]').select_option('Verified');act('save-task')
 check('Verification guard rejects incomplete checklist',page.locator('[role="dialog"]').count()==1)
 for i in range(3):page.locator(f'[name="check{i}"]').check()
 shot('work-item-editor-dark');act('save-task')
 check('Verified status requires completed checks',page.evaluate('CIPrototype.state.tasks.at(-1).status')=='Verified')
 page.locator('[data-input="workbench-query"]').fill('QA test')
 check('Work-item search filters cards',page.locator('.task-card').count()==1)
 page.locator('[data-input="workbench-query"]').fill('')
 # Drag between non-verified columns via native drag-and-drop.
 page.locator('[data-drag="RF-001"]').drag_to(page.locator('[data-drop="Planned"]'))
 check('Drag-and-drop updates work-item status',page.evaluate('CIPrototype.state.tasks.find(t=>t.id==="RF-001").status')=='Planned')
 nav('report');page.locator('#audit-note').fill('QA note: review the persistence boundary.');act('report-note')
 check('Audit note appears in report', 'QA note:' in page.locator('#report-paper').inner_text())
 page.locator('[data-change="report-section"][data-key="security"]').uncheck()
 check('Report content switches remove section','04 / Security review' not in page.locator('#report-paper').inner_text())
 with page.expect_download(timeout=3000) as dl:act('export-report')
 d=dl.value;d.save_as(ROOT/'tests'/'test-export-report.md')
 check('Markdown report export creates a real download',d.suggested_filename=='codebase-audit-report.md')
 check('Export contains current reviewer note','QA note:' in (ROOT/'tests'/'test-export-report.md').read_text(encoding='utf-8'))
 with page.expect_download(timeout=3000) as dl:page.evaluate('CIPrototype.actions["export-state"]()')
 dl.value.save_as(ROOT/'tests'/'test-review-state.json')
 saved=json.loads((ROOT/'tests'/'test-review-state.json').read_text(encoding='utf-8'))
 check('Review state export has explicit schema',saved['schema']=='codebase-inspector.review-state.v1')
 nav('sources');act('import-state');page.locator('#state-import-file').set_input_files(ROOT/'tests'/'test-review-state.json');act('confirm-import');page.wait_for_timeout(50)
 check('Exported review state imports successfully',page.locator('[role="dialog"]').count()==0)
 invalid=ROOT/'tests'/'test-invalid-state.json';invalid.write_text('{"schema":"not-supported","state":{}}')
 act('import-state');page.locator('#state-import-file').set_input_files(invalid);act('confirm-import');page.wait_for_timeout(30)
 check('Unsupported state schema is rejected',page.locator('[role="dialog"]').count()==1);page.keyboard.press('Escape')
 act('source-wizard');shot('source-wizard-dark');page.locator('[data-action="wizard-type"][data-type="External directory"]').click();act('wizard-next')
 page.locator('#wizard-name').fill('Review fixture');page.locator('#wizard-path').fill('C:/Projects/example');act('wizard-next');shot('source-confirmation-dark');act('wizard-finish')
 check('Source wizard changes metadata only',page.evaluate('CIPrototype.state.sourceName')=='Review fixture')
 for v in ['failed','stale','empty','complete']:
  page.locator(f'[data-action="scan-state"][data-state="{v}"]').click();shot(f'scan-{v}-dark')
 check('All four recoverable scan states render')
 act('scan');page.wait_for_timeout(800);shot('scan-progress-dark');page.wait_for_timeout(1600)
 check('Demo scan completes',page.locator('#scan-stage-label').inner_text()=='Demo evidence is ready.');page.keyboard.press('Escape')
 page.keyboard.press('Control+k');page.locator('#command-input').fill('CostEngine');shot('command-palette-dark');page.keyboard.press('ArrowDown');page.keyboard.press('Enter');page.wait_for_timeout(60)
 check('Keyboard command palette opens a file',page.locator('main h1').inner_text()=='CostEngine.ts')
 nav('settings');page.locator('[data-change="theme"]').select_option('light')
 check('Light theme applies',page.locator('html').get_attribute('data-theme')=='light')
 for r in ['city','overview','architecture','quality','tests','dependencies','security','evolution','ownership','workbench','report','sources','settings','file','hotspots']:
  # Restore primary tabs for screenshots.
  page.evaluate('Object.assign(CIPrototype.state,{cityMode:"city",cityMetric:"risk",cityHeight:"complexity",archTab:"map",qualityStatus:"Open",testTab:"coverage",dependencyTab:"inventory",dependencyFilter:"All dependencies",securityTab:"advisories",workbenchQuery:"",sourceName:"sample-workspace",sourceType:"Vault directory",sourcePath:"projects/sample-codebase",selected:"domain-0",notes:"Validate entry points before removing unused code. Confirm intended Domain and Storage boundaries."})')
  nav(r);shot(r+'-light')
 check('All 15 screens render in light theme')
 # Restore dark, narrow layout smoke test.
 page.evaluate('CIPrototype.state.theme="dark";CIPrototype.render()')
 page.set_viewport_size({'width':390,'height':844})
 for r in ['city','overview','architecture','quality','tests','dependencies','security','evolution','ownership','workbench','report','sources','settings','file','hotspots']:
  nav(r);check(f'Narrow layout: {r} has no document overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  if r in ['city','overview','architecture','workbench','settings']:shot(r+'-narrow')
 act('menu');check('Narrow navigation opens',page.locator('.sidebar').get_attribute('class').endswith('open'));page.keyboard.press('Escape')
 check('No uncaught JavaScript errors',len(errors)==0)
 check('No network requests during render and interactions',len(network)==0)
 result={'checksPassed':len(checks),'checks':checks,'jsErrors':errors,'networkRequests':network,'browser':'Chromium, 1600×1050 and 390×844','method':'set_content: managed browser blocks file:// and localhost URL navigation. Real browser-localStorage reload not tested in this harness.'}
 (ROOT/'tests'/'interaction-results.json').write_text(json.dumps(result,indent=2));print(json.dumps(result,indent=2))
 browser.close()
